name: publish ui package

on:
        push:
                branches: ["prod"]

jobs:
        build:
                runs-on: ubuntu-latest
        steps:
                - name: Checkout
                  uses: actions/checkout@v3
                - name: Use Node.js 18
                  uses: actions/setup-node@v3
                  with:
                        node-version: "18.x"
                             
                - name: Install npm Packages
                  run: npm install
                        	
                - name: install sementic-release
                  run: npm i semantic-release
                        	
                - npm: build
                  run: npm run build
                        	
                - npm: publish to npmjs
                  run: npm run publish
                        	
                - npm: package release
                  env:
                          NPM_ACCESS_TOKEN: ${{secrets.NPM_ACCESS_TOKEN}}
                  run: npx semantic-release
                  
